version: '2.1'

services:
    zookeeper:
        image: riguz/zookeeper:3.6.1
        ports:
            - 2181:2181
    kafka:
        image: riguz/kafka:2.5.0
        depends_on:
            zookeeper:
                condition: service_healthy
        ports:
            - 9092:9092
        links:
            - zookeeper
        environment:
            - ZOOKEEPER_SERVERS=zookeeper:2181
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=IwEEJznUbX3a
            - MYSQL_DATABASE=eventstore
            - MYSQL_USER=tiger
            - MYSQL_PASSWORD=MRSkmXE2RINm
        volumes:
            - ./mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
